apiVersion: rkeprep/v1
kind: Server
metadata:
  name: j64manager-ctrl02
spec:
  ip: 10.0.4.132
  prefix: 24
  gateway: 10.0.4.1
  hostname: j64manager-ctrl02
  dns: ["10.0.1.34", "10.231.1.34"]
  searchDomains: ["dev.kube", "dev.local"]
