apiVersion: rkeprep/v1
kind: Server
metadata:
  name: copine-ctrl01
spec:
  ip: 10.0.69.55
  prefix: 27
  gateway: 10.0.69.33
  hostname: copine-ctrl01
  dns: ["172.16.69.71", "172.16.69.72"]
  searchDomains: ["dev.kube", "dev.local"]

  write-kubeconfig-mode: "0640"
  tls-san:
    - copine-cluster
    - copine-cluster.dev.kube
    - 10.0.69.55
    - 10.0.69.56
    - 10.0.69.57
  #node-label:
  #  - role=control-plane
  service-cidr: 10.96.0.0/12
  cluster-cidr: 10.42.0.0/16
  cluster-domain: cluster.local
  cni: canal
  enable-servicelb: "false"
  system-default-registry: altregistry.dev.kube
  private-registry: /etc/rancher/rke2/registries.yaml
  kube-apiserver-arg:
    - "audit-log-maxage=15"

  # Optional: your CA handling
  customCA:
    rootCrt: /certs/dev-certa001-ca-dev-local.crt
    rootKey: /certs/dev-certa001-ca-dev-local-key.pem
    # intermediateCrt: /certs/intermediate.crt
    # intermediateKey: /certs/intermediate.key
    installToOSTrust: true
