apiVersion: rkeprep/v1
kind: Server
metadata:
  name: copine-ctrl01
spec:
  ip: 10.0.69.55
  prefix: 27
  gateway: 10.0.69.33
  hostname: copine-ctrl01
  dns: ["172.16.69.71", "172.16.69.72"]
  searchDomains: ["cantrellcloud.net", "cantrelloffice.cloud"]

  write-kubeconfig-mode: "0640"
  tls-san:
    - copine-ctrl01
    - copine-ctrl01.cantrellcloud.net
    - 10.0.69.55
  node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"
  node-label:
  - "env=preprod"
  service-cidr: 10.96.0.0/12
  cluster-cidr: 10.42.0.0/16
  cluster-domain: cluster.local
  cni: canal
  system-default-registry: altregistry.dev.kube
  private-registry: /etc/rancher/rke2/registries.yaml
  enable-servicelb: false
  kube-apiserver-arg:
    - audit-log-maxage=15

  # Optional: your CA handling
  customCA:
    rootCrt: certs/rke2-cert.crt
    rootKey: certs/rke2-cert-key.pem
    installToOSTrust: true