apiVersion: rkeprep/v1
kind: Agent
metadata:
  name: r01domain-worker1
spec:
  ip: 10.0.4.134
  prefix: 24
  gateway: 10.0.4.1
  hostname: r01domain-worker1
  dns: ["10.0.1.34", "10.231.1.34"]
  searchDomains: ["dev.kube", "dev.local"]
  serverURL: https://10.0.4.131:9345
  token: 
