apiVersion: rkeprep/v1
kind: Image
metadata:
  name: offline-prep
spec:
  defaultDns: ["10.0.1.34", "10.231.1.34"]
  defaultSearchDomains: ["corp.local", "dev.kube"]
  registry: rke2registry.dev.local/rke2
  registryUsername: admin
  registryPassword: ZAQwsx!@#123
