apiVersion: rkeprep/v1
kind: Server
metadata:
  name: cluster1-server1
spec:
  ip: 10.0.0.10
  prefix: 24
  hostname: cluster1-server1
  dns: ["10.0.1.34", "10.231.1.34"]
  searchDomains: ["corp.local", "dev.kube"]
